# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ddanciu <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/09/16 21:05:05 by ddanciu           #+#    #+#              #
#    Updated: 2014/09/16 21:06:39 by ddanciu          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all : gcc -Wall -Wextra -Werror ft_atoi.c ft_putchar.c ft_strlen.c ft_putstr.c ft_putnbr.c operations.c operators.c main.c -o do-op

clean:
	rm -rf do-op
